# Generated by Django 3.2.3 on 2021-06-04 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_foo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
